[tool.bumpver]
current_version = "2023.3.0"
version_pattern = "YYYY.MM.INC0"
commit_message = ":bookmark: Bump version {old_version} -> {new_version}"
commit = true
push = false  # disabled for GitHub Actions
tag = true

[tool.bumpver.file_patterns]
"frontmatter_cli/__init__.py" = [
    '__version__ = "{version}"',
]

"frontmatter_cli/cli.py" = [
    '__version__ = "{version}"',
]

"setup.cfg" = [
    'version = {version}',
]
